"""
Student information for this assignment:

Replace <Saisrikar Kichili> with your name.
On my/our honor, <Saisrikar Kichili> and <Anika Koppula>, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: srk2749
UT EID 2: ark3398
"""


# Iterates over a 2D list from left to right, then top to bottom
# and returning the coordinates (row, column).
def row_major_traversal(grid):
    x = []
    for i in range(len(grid)):
        for j in range(len(grid[i])):
            x.append((i, j))
    return x


# Iterates over a 2D list from left to right, then top to bottom
# and returning the coordinates (row, column).
def column_major_traversal(grid):
    x = []
    for i in range(len(grid)):
        for j in range(len(grid[i])):
            x.append((j, i))
    return x


# Iterates over a 2D list from top to bottom then left to right
# and returning the coordinates (row, column).
def row_zigzag_traversal(grid): 
    x = []
    for i in range(len(grid)):
        if i % 2 == 0:
            for j in range(len(grid[i])):
                x.append((i, j))
        else:
            for j in range(len(grid[i]) - 1, -1, -1):
                x.append((i, j))
    return x


# Iterates over a 2D list by alternating between iterating
# left to right and right to left, going from top to bottom
# and returning the coordinates (row, column).
def column_zigzag_traversal(grid):
    x = []
    for i in range(len(grid)):
        if i % 2 == 0:
            for j in range(len(grid[i])):
                x.append((j, i))
        else:
            for j in range(len(grid[i]) - 1, -1, -1):
                x.append((j, i))
    return x


# Iterates over a 2D list from the top-right to the bottom-left
# in the direction of the main diagonal and returning the
# coordinates (row, column).
def main_diagonal_traversal(grid):
    x = []
    for i in range(len(grid[0])):
        y = 0
        z = i
        while z >= 0 and y < len(grid):
            x.append((y, z))
            y += 1
            z -= 1
    for j in range(1, len(grid)):
        y = j
        z = len(grid[0])
        while z >= 1 and y < len(grid):
            x.append((y,z))
            y += 1
            z -= 1
    return x

# Iterates over a 2D list from the top-left to the bottom-right
# in the direction of the secondary diagonal and returning the
# coordinates (row, column).
def secondary_diagonal_traversal(grid):
    x = []
    for i in range(len(grid)):
        y = i
        z = 0
        while z < len(grid[0]) and y >= 0:
            x.append((y, z))
            y -= 1
            z += 1
    for j in range(1, len(grid[0])):
        y = len(grid) - 1
        z = j
        while z < len(grid[0]) and y >= 0:
            x.append((y, z))
            y -= 1
            z += 1
    return x


# Iterates over a 2D list in spiral order and returning the
# coordinates (row, column).
def spiral_traversal(grid):
    return []
